#!/bin/bash

# Debian清华源配置脚本 - Debian 13 (trixie)
# GitHub仓库使用说明：https://github.com/yourusername/debian-mirror-script

set -e  # 出现错误立即退出

# 检测是否为root用户
if [[ $EUID -ne 0 ]]; then
   echo "错误：此脚本必须以root权限运行" 
   echo "请使用 'sudo bash $0'"
   exit 1
fi

# 配置参数
DEBIAN_VERSION="trixie"
SOURCE_DIR="/etc/apt/sources.list.d"
SOURCE_FILE="${SOURCE_DIR}/debian.sources"
BACKUP_FILE="${SOURCE_FILE}.bak.$(date +%Y%m%d%H%M%S)"
MIRROR_URL="https://mirrors.tuna.tsinghua.edu.cn/debian"
SECURITY_URL="https://mirrors.tuna.tsinghua.edu.cn/debian-security"
KEYRING="/usr/share/keyrings/debian-archive-keyring.gpg"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # 重置颜色

# 显示标题
echo -e "${GREEN}\n===== Debian 清华源配置脚本 =====${NC}"
echo -e "目标版本: ${YELLOW}Debian ${DEBIAN_VERSION}${NC}"
echo -e "镜像地址: ${YELLOW}${MIRROR_URL}${NC}\n"

# 备份原有配置文件
if [[ -f $SOURCE_FILE ]]; then
    echo -e "${YELLOW}>> 备份原有源文件: $SOURCE_FILE -> $BACKUP_FILE${NC}"
    cp $SOURCE_FILE $BACKUP_FILE
else
    echo -e "${YELLOW}!! 未找到原有配置文件，将创建新文件${NC}"
fi

# 生成新的源配置
echo -e "${YELLOW}>> 生成清华源配置...${NC}"
cat > $SOURCE_FILE <<EOF
# Debian ${DEBIAN_VERSION} 清华镜像源配置
# Generated by Tsinghua Mirror Script ($(date))
# GitHub: https://github.com/yourusername/debian-mirror-script

# 主仓库
Types: deb
URIs: ${MIRROR_URL}
Suites: ${DEBIAN_VERSION} ${DEBIAN_VERSION}-updates ${DEBIAN_VERSION}-backports
Components: main contrib non-free non-free-firmware
Signed-By: ${KEYRING}

# 安全更新仓库
Types: deb
URIs: ${SECURITY_URL}
Suites: ${DEBIAN_VERSION}-security
Components: main contrib non-free non-free-firmware
Signed-By: ${KEYRING}

# 以下为源码仓库配置(默认注释)
# Types: deb-src
# URIs: ${MIRROR_URL}
# Suites: ${DEBIAN_VERSION} ${DEBIAN_VERSION}-updates ${DEBIAN_VERSION}-backports
# Components: main contrib non-free non-free-firmware
# Signed-By: ${KEYRING}

# Types: deb-src
# URIs: ${SECURITY_URL}
# Suites: ${DEBIAN_VERSION}-security
# Components: main contrib non-free non-free-firmware
# Signed-By: ${KEYRING}
EOF

# 验证配置
echo -e "${YELLOW}>> 配置文件内容:${NC}"
echo "--------------------------------------"
cat $SOURCE_FILE
echo "--------------------------------------"

# 更新软件包索引
echo -e "\n${YELLOW}>> 正在更新软件包索引...${NC}"
apt update

# 完成提示
echo -e "${GREEN}\n✔ 清华源配置成功完成!${NC}"
echo -e "以下命令可以验证配置:"
echo -e "  ${YELLOW}apt policy${NC}        # 检查源优先级"
echo -e "  ${YELLOW}apt update${NC}        # 手动更新索引"
echo -e "  ${YELLOW}grep -i tuna ${SOURCE_FILE}${NC}  # 检查镜像源"
echo -e "\n如遇到问题，原配置已备份至: ${YELLOW}${BACKUP_FILE}${NC}"
