name: Release Shell Scripts

on:
  push:
    branches: [ main ]

jobs:
  publish-scripts:
    # 权限设置需要放在job级别
    permissions:
      contents: read
      releases: write  # Release权限必须显式声明
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          # 使用官方安装脚本确保最新版
          curl -LO https://github.com/cli/cli/releases/latest/download/gh_1.0.0_linux_amd64.deb
          sudo dpkg -i gh_1.0.0_linux_amd64.deb
          
      - name: Generate timestamp version
        id: timestamp
        run: |
          echo "version=$(date -u '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.timestamp.outputs.version }} \
            --title "Shell Scripts ${{ steps.timestamp.outputs.version }}" \
            --notes "Automated release at $(date)" \
            --notes-start-tag ""
          
      - name: Upload scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 更健壮的文件处理方式
          find . -name '*.sh' -print0 | while IFS= read -r -d $'\0' file; do
            echo "Uploading: '$file'"
            gh release upload "$version" "$file" --clobber
          done
        shell: bash
