name: Release Shell Scripts

on:
  push:
    branches: [ main ]

jobs:
  publish-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          # 官方安装方式 (比 apt 版本更新)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
          sudo apt update && sudo apt install gh -y

      - name: Generate timestamp
        id: timestamp
        run: |
          echo "version=$(date -u '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.timestamp.outputs.version }} \
            --title "Scripts ${{ steps.timestamp.outputs.version }}" \
            --notes "Automated shell script release"

      - name: Upload scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 处理含空格/特殊字符的文件名
          find . -name '*.sh' -print0 | while IFS= read -r -d '' file; do
            gh release upload ${{ steps.timestamp.outputs.version }} "$file"
          done
