name: Release Shell Scripts

on:
  push:
    branches: [ main ]

jobs:
  publish-scripts:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Generate timestamp version
        id: timestamp
        run: |
          echo "version=$(date -u '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.timestamp.outputs.version }}" \
            --title "Shell Scripts ${{ steps.timestamp.outputs.version }}" \
            --notes "Automated release at $(date)" \
            --clobber

      - name: Upload scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ steps.timestamp.outputs.version }}"
          find ./ -type f -name "*.sh" -not -path "./.git/*" -not -path "./.github/*" -print0 | while IFS= read -r -d $'\0' file; do
            echo "Uploading: '$file'"
            chmod +x "$file"
            gh release upload "$version" "$file" --clobber
          done
        shell: bash
