name: Release Shell Scripts

on:
  push:
    branches: [ main ]

permissions: # 关键权限设置
  releases: write # 显式授予Release写权限
  contents: read  # 读取仓库内容权限

jobs:
  publish-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Generate timestamp version
        id: timestamp
        run: |
          echo "version=$(date -u '+%Y%m%d%HM%S')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.timestamp.outputs.version }} \
            --title "Scripts ${{ steps.timestamp.outputs.version }}" \
            --notes "Automated shell script release"

      - name: Upload scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 处理特殊字符的文件名
          while IFS= read -r -d '' file; do
            echo "Uploading: $file"
            gh release upload ${{ steps.timestamp.outputs.version }} "$file" || echo "Upload failed: $file"
          done < <(find . -name '*.sh' -print0)
        continue-on-error: true
